---
- name: Bootstrap management server for basekit role
  hosts: "{{ target_hosts | default('mgmt_kvm') }}"
  become: true

  tasks:
    - name: Install required packages
      yum:
        name:
          - "@Development Tools"
          - "@Virtualization Platform"
          - "@Container Management"
          - "@Headless Management"
          - gcc
          - openssl-devel
          - bzip2-devel
          - libffi-devel
          - zlib-devel
          - xz-devel
          - readline-devel
          - sqlite-devel
          - wget
          - virt-install
          - cockpit-machines
          - libcdio
          - libguestfs
        state: present
        disable_gpg_check: yes

    - name: Start/Enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - libvirtd
        - cockpit