version: '3'

includes:
  main:
    taskfile: /openspace/Taskfile.yml

tasks:
  #============================================================================
  # GEP1 Deployment Tasks
  #============================================================================
  deploy-gep1:
    desc: "Deploy GEP1 Environment"
    cmds:
      - task: main:init
      - task: main:deploy-infra-basekit
      - task: main:deploy-mcm

  destroy-gep1:
    desc: "Destroy GEP1 Environment"
    cmds:
      - task: main:destroy-mcm
      - task: main:destroy-infra-basekit